version : "2.1"
services:
  eureka:
    image: microservice/discovery_service
    container_name: eureka
    build:
      context: .
      dockerfile: ./Discovery_service/Dockerfile
    hostname: eureka
    ports:
      - "8761:8761"
    networks:
      - common-network

  gateway:
    image: microservice/gateway
    container_name: gateway
    build:
      context: .
      dockerfile: ./Gateway_service/Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - eureka
    networks:
      - common-network

  authservice:
    image: microservice/authservice
    container_name: authservice
    build:
      context: .
      dockerfile: ./Authorization_service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=user
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=Movie_theater
      - DATABASE_PORT=3306
    depends_on:
      - mysqldb
      - eureka
    networks:
      - common-network

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Movie_theater
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    ports:
      - 3307:3306
    volumes:
      - /data/mysql
    networks:
      - common-network

  movie:
    image: microservice/movie
    container_name: movie
    build:
      context: .
      dockerfile: ./SubServices/movieService/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=user
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=Movie_theater
      - DATABASE_PORT=3306
    depends_on:
      - mysqldb
      - eureka
    volumes:
      - /data/movie_theater
    networks:
      - common-network

#Docker Networks
networks:
  common-network:
    driver: bridge
#networks:
#  microservicesnet: